version: "2"
services:
  pkg_sender_test:
    build: .
    container_name: pkg_sender_test
    volumes:
      - ./files:/opt/apps/pkg_sender_test/files
      - /srv/dev-disk-by-uuid-820dec2c-37a0-45b3-af55-34fb34afe767/:/HDD1
    ports:
      - 3334:8080
    environment:
      - PORT=8080
      - STATIC_FILES=/opt/apps/pkg_sender_test/files
      - LOCALIP=192.168.0.104
      - PS4IP=192.168.0.102
    restart: unless-stopped
