version: "2"
services:
  pkg_sender_test:
    build: .
    container_name: pkg_sender_test
    volumes:
      - ./files:/opt/apps/pkg_sender_test/files
      - /srv/dev-disk-by-uuid-820dec2c-37a0-45b3-af55-34fb34afe767/:/HDD1
      - /srv/dev-disk-by-uuid-b3ad2233-4667-446a-b212-d28e547d6fb2/:/HDD2
      - /srv/dev-disk-by-uuid-1913d119-ecc4-41e4-b936-348064e82870/:/HDD3
    ports:
      - 3334:8034
    environment:
      - PORT=8034
      - STATIC_FILES=/opt/apps/pkg_sender_test/files
      - LOCALIP=192.168.0.104
      - PS4IP=192.168.0.102
    restart: unless-stopped
